baseURL = '/'
languageCode = 'en-us'
title = 'Minicode'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  description = 'Small tools and notes from the Minicode project.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
