config:
  aws:region: us-west-2
  minicode-site:hostedZoneName: seanholung.com
  minicode-site:sites:
    - name: minicode
      resourcePrefix: site
      domainName: minicode.seanholung.com
      certificateArn: arn:aws:acm:us-east-1:127590312302:certificate/2b25457c-334d-4e02-b013-a49994f5e67a
    - name: claudepanion
      resourcePrefix: claudepanion
      domainName: claudepanion.seanholung.com
