config:
  aws:region: us-west-2
  minicode-site:domainName: minicode.seanholung.com
  minicode-site:hostedZoneName: seanholung.com
  minicode-site:certificateArn: arn:aws:acm:us-east-1:127590312302:certificate/16e3cd20-3661-4c77-a4f1-550be34e93f9
encryptionsalt: v1:vpSlOy4gWM4=:v1:5b6qPpBQ4WbFJz7k:6HrnaoSS5zC/ItxrGhsOt5JLY7hEFw==
